var situations = {
        '0': "Mensen vertrekken na 10 minuten",
        '1': "10 brakke hoofden in de zaal",
        '2': "Mensen studeren andere vakken",
        '3': "Etende mensen",
        '4': "Freek loopt rond",
        '5': "Microfoon heeft nieuwe batterijen nodig",
        '6': "Mensen met bontkraag aan tijdens college",
        '7': "Ze interpreteert de vraag verkeerd",
        '8': "Staartmans gaat praten",
        '9': "Mensen komen veels te laat binnen",
        '10': "Freek kan weer eens niet gewoon engels praten",
        '11': "Microfoon gooien gaat in 1 keer goed",
        '12': "Pinho kijkt de zaal in",
        '13': "Er zijn memes gemaakt tijdens de lecture",
        '14': "Er gaat weer eens iets mis in de dia's",
        '15': "Iemands telefoon gaat af",
        '16': "Iemand gooit de microfoon verkeerd",
        '17': "Freek vonk kijkt boos om",
        '18': "Mensen die aan het gamen zijn tijdens college",
        '19': "Ze dreigt met het niet afkrijgen van de powerpoint",
        '20': "De microfoon werkt niet",
        '21': "Antwoord op een vraag is fout",
        '22': "Niemand zit naast freek vonk",
        '23': "Wachten tot iedereen stil is",
        '24': "Iemand slaapt tijdens college",
        '25': "Calculus cijfer is bekend",
        '26': "'Ask your neighbour'",
        '27': "'You can do this at home'",
        '28': "Three/Tree",
        '29': "Node/Note",
        '30': "De lecture is weer exclusief voor TW",
        "31": "Niemand durft bingo te roepen",
        "32": "Iemand roept bingo",
        "33": "Iemand stelt een vraag over de stof van volgende week",
        "34": "Microfoon komt tegen iemands hoofd aan",
        "35": "Niemand geeft antwoord op de gestelde vraag",
        "36": "Microfoon valt op de grond"
};

module.exports = {
        situations: situations
}
